namespace TicketFlow.Application.DTOs;

public record CreateOrderRequest(
    Guid TicketId,
    Guid UserId,
    // IdempotencyKey: generated by the client (e.g. UUID v4).
    // If the same order arrives twice, the second is rejected.
    string IdempotencyKey
);
